### ISSUE TITLE
Gemma3n bad merge causes runtime error

### ISSUE THREAD

**Issue by colintheshots** [ml-explore/mlx-swift-examples#364]
Gemma3 should only appear once in the dictionary within LLMModelFactory, but due to a bad merge, it was duplicated instead of moved. main no longer builds.

Swift/Dictionary.swift:830: Fatal error: Dictionary literal contains duplicate keys

```

    /// All predefined model types.
    private static func all() -> [String: @Sendable (URL) throws -> any LanguageModel] {
        [
            "mistral": create(LlamaConfiguration.self, LlamaModel.init),
// ...
            "gemma2": create(Gemma2Configuration.self, Gemma2Model.init),
            "gemma3": create(Gemma3TextConfiguration.self, Gemma3TextModel.init), // correct location
            "gemma3_text": create(Gemma3TextConfiguration.self, Gemma3TextModel.init), // correct location
            "gemma3n": create(Gemma3nTextConfiguration.self, Gemma3nTextModel.init),
            "qwen2": create(Qwen2Configuration.self, Qwen2Model.init),
            "qwen3": create(Qwen3Configuration.self, Qwen3Model.init),
            "qwen3_moe": create(Qwen3MoEConfiguration.self, Qwen3MoEModel.init),
            "starcoder2": create(Starcoder2Configuration.self, Starcoder2Model.init),
            "cohere": create(CohereConfiguration.self, CohereModel.init),
            "openelm": create(OpenElmConfiguration.self, OpenELMModel.init),
            "internlm2": create(InternLM2Configuration.self, InternLM2Model.init),
            "deepseek_v3": create(DeepseekV3Configuration.self, DeepseekV3Model.init),
            "gemma3_text": create(Gemma3TextConfiguration.self, Gemma3TextModel.init), // incorrect location
            "gemma3": create(Gemma3TextConfiguration.self, Gemma3TextModel.init), // incorrect location
            "granite": create(GraniteConfiguration.self, GraniteModel.init),
// ...
            "exaone4": create(Exaone4Configuration.self, Exaone4Model.init),
        ]
    }
```

**Comment by colintheshots** [comment]
Fixed.
